ALTER TABLE pages
ADD COLUMN hero_title VARCHAR(255) DEFAULT NULL,
ADD COLUMN hero_subtitle TEXT DEFAULT NULL,
ADD COLUMN main_content LONGTEXT DEFAULT NULL,
ADD COLUMN show_contact_form BOOLEAN DEFAULT FALSE,
ADD COLUMN show_packages BOOLEAN DEFAULT FALSE;
