ALTER TABLE pages
ADD COLUMN about_hero_title VARCHAR(255) DEFAULT NULL,
ADD COLUMN about_hero_subtitle TEXT DEFAULT NULL,
ADD COLUMN about_mission_heading VARCHAR(255) DEFAULT NULL,
ADD COLUMN about_mission_text TEXT DEFAULT NULL,
ADD COLUMN about_mission_image VARCHAR(255) DEFAULT NULL,
ADD COLUMN about_founder_heading VARCHAR(255) DEFAULT NULL,
ADD COLUMN about_founder_name VARCHAR(255) DEFAULT NULL,
ADD COLUMN about_founder_title VARCHAR(255) DEFAULT NULL,
ADD COLUMN about_founder_quote TEXT DEFAULT NULL,
ADD COLUMN about_founder_image VARCHAR(255) DEFAULT NULL;
